export default {
    LOGIN: "login",
    SIGNUP: "Signup",
    OTP_VERIFICATION: 'OtpVerification',
    Create_New_Password: 'CreateNewPassword',
    HOME: "home",
    PROFILE: "profile",
    TAB_ROUTES: "tabRouts",
    MY_ORDER: "myorder",
    Nearby_Medical: "nearbymedical",
    // Confirm_Password: "confirmPassword",
    Forgot_Password: "forgotPassword",
    Medical_Profile: "medicalProfile",
    Physiotherepist_Profile: "physiotherepistProfile",
    EditPhysiotherepist_Profile: "EditPhysiotherepistProfile",
    Doctor_Profile: "doctorProfile",
    Laboratory_Profile: "laboratoryProfile",
    Chemist_Profile: "ChemistProfile",
    DIAGNOSTIC_PROFILE: "Diagnostic_Profile",
    EDIT_LABORATORY_PROFILE_MODAL: "EditLaboratoryProfileModal",
    EditDoctorProfile: "EditdoctorProfile",
    ProfileCreate: "profileCreate",
    PAYMENT: "Payment",
    UPLOAD_PRESCIPTION: "Upload_Presciption",
    HomeChemist: "HomeChemist",
    CompleteOrder: "CompleteOrder",
    PendingOrder: "PendingOrder",

};