import Doctor_Profile from './Doctor_Profile/Doctor_Profile';

export {default as OtpVerification} from './OtpVerification/OtpVerification';
export {default as Login} from './Login/Login';
export {default as Signup} from './Signup/Signup';
export {default as Home} from './Home/Home';
export {default as Profile} from './Profile/Profile';
export {default as Nearby_Medical} from './Nearby_Medical/Nearby_Medical';
export {default as MyOrder} from './MyOrder/MyOrder';
// export {default as Confirm_Password} from './Confirm_Password/Confirm_Password';
export {default as Forgot_Password} from './Forgot_Password/Forgot_Password';
export {default as Create_New_Password} from './Create_New_Password/Create_New_Password';
export {default as Medical_Profile} from './Medical_Profile/Medical_Profile';
export {default as EditLaboratoryProfileModal} from './EditLaboratoryProfileModal/EditLaboratoryProfileModal';

export {default as Physiotherepist_Profile} from './Physiotherepist_Profile/Physiotherepist_Profile';
export {default as EditPhysiotherepist_Profile} from './EditPhysiotherepist_Profile/EditPhysiotherepist_Profile';
export {default as Doctor_Profile} from './Doctor_Profile/Doctor_Profile';
export {default as EditDoctorProfile} from './EditDoctorProfile/EditDoctorProfile';
export {default as Laboratory_Profile} from './Laboratory_Profile/Laboratory_Profile';
export {default as Diagnostic_Profile} from './Diagnostic_Profile/Diagnostic_Profile';
export {default as Chemist_Profile} from './Chemist_Profile/Chemist_Profile';
export {default as Upload_Presciption} from './Upload_Presciption/Upload_Presciption';
export {default as Payment} from './Payment/Payment';
export {default as HomeChemist} from './HomeChemist/HomeChemist';
export {default as UserOrderDetails} from './UserOrderDetails/UserOrderDetails';
export {default as CompleteOrder} from './CompleteOrder/CompleteOrder';
export {default as PendingOrder} from './PendingOrder/PendingOrder';
export {default as ChemistOrderDetails} from './ChemistOrderDetails/ChemistOrderDetails';
export {default as profileCreate} from '../Components/ProfileCreate';
export {default as Physiotherapist_Screen} from './Physiotherepist_Screen/Physiotherapist_Screen';
export {default as Laboratory_Screen} from './Laboratory_Screen/Laboratory';
export {default as Diagnostic_Screen} from './Diagnostic_Screen/Diagnoistic_Screen';
export {default as ChemistBankDetails} from '../Components/ChemistBankDetails';
export {default as DoctorCreate} from '../Components/DoctorCreate';
export {default as ChemistCreate} from '../Components/ChemistCreate';
export {default as ProfileCreateDiagnos} from '../Components/ProfileCreateDiagnos';
export {default as ProfileCreateLab} from '../Components/ProfileCreateLab';
export {default as ProfileCreatePhysio} from '../Components/ProfileCreatePhysio';