export const LOGIN = "LOGIN";
export const SIGNUP = "SIGNUP";
export const LOGOUT = "LOGOUT";
// export const LOGIN_LOADER = "LOGIN_LOADER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const OTP_VERIFICTION = "OTP_VERIFICTION";
export const NEW_PASSWORD = "NEW_PASSWORD";
export const CHEMIST_PROFILE_REGISTER = "CHEMIST_PROFILE_REGISTER";
export const DOCTOR_PROFILE_REGISTER = "DOCTOR_PROFILE_REGISTER";
export const GET_DOCTOR = "GET_DOCTOR";
export const EDIT_DOCTOR_PROFILE = "EDIT_DOCTOR_PROFILE";
export const DIAGNOSTIC_PROFILE_REGISTER = "DIAGNOSTIC_PROFILE_REGISTER";
export const GET_DIAGNOSTIC_PROFILE = "GET_DIAGNOSTIC_PROFILE";
export const EDIT_DIAGNOSTIC_PROFILE = "EDIT_DIAGNOSTIC_PROFILE";
export const GET_CHEMIST = "GET_CHEMIST"
export const GET_ALL_CHEMIST_PROFILE = "GET_ALL_CHEMIST_PROFILE"
export const LABORATORY_PROFILE = "LABORATORY_PROFILE"
export const GET_LABORATORY_PROFILE = "GET_LABORATORY_PROFILE"
export const EDIT_LABORATORY_PROFILE = "EDIT_LABORATORY_PROFILE"
export const CHEMIST_PROFILE = "CHEMIST_PROFILE"
export const GET_CHEMIST_PROFILE = "GET_CHEMIST_PROFILE"
export const EDIT_CHEMIST_PROFILE = "EDIT_CHEMIST_PROFILE"
export const PHYSIOTHERAPIST_PROFILE = "PHYSIOTHERAPIST_PROFILE"
export const GET_PHYSIOTHERAPIST_PROFILE = "GET_PHYSIOTHERAPIST_PROFILE"
export const EDIT_PHYSIOTHERAPIST_PROFILE = "EDIT_PHYSIOTHERAPIST_PROFILE"
export const ORDER_PLACE = "ORDER_PLACE"
export const GET_PENDING_ORDER = "GET_PENDING_ORDER"
export const GET_COMPLETED_ORDER = "GET_COMPLETED_ORDER"
export const EDIT_ORDER_PLACE = "EDIT_ORDER_PLACE"
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS"
export const GET_DOCTOR_PROFILE = 'GET_DOCTOR_PROFILE';



